# Generated by Django 4.0.4 on 2022-05-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_partnercategorymodel_partnersmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopagemodel',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='infopagemodel',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='infopagemodel',
            name='body_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='infopagemodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='infopagemodel',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='infopagemodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnercategorymodel',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnercategorymodel',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnercategorymodel',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='title_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='title_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='title_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='statsmodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='statsmodel',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='statsmodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
