# Generated by Django 4.0.4 on 2022-05-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aboutinfomodel_certificatesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutinfomodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutinfomodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutinfomodel',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
