# Generated by Django 4.0.4 on 2022-05-15 06:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_aboutinfomodel_title_en_aboutinfomodel_title_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutinfomodel',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterField(
            model_name='infopagemodel',
            name='title',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='infopagemodel',
            name='title_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='infopagemodel',
            name='title_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='infopagemodel',
            name='title_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
