# Generated by Django 4.0.4 on 2022-05-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_infopagemodel_body_alter_infopagemodel_body_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopagemodel',
            name='slug',
            field=models.SlugField(blank=True, default=1, unique=True),
            preserve_default=False,
        ),
    ]
