# Generated by Django 4.0.4 on 2022-05-15 08:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_infopagemodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vacancies',
                'verbose_name_plural': 'Vacancies',
            },
        ),
        migrations.AlterModelOptions(
            name='servicesmodel',
            options={'verbose_name': 'Our services', 'verbose_name_plural': 'Our services'},
        ),
    ]
