# Generated by Django 4.0.4 on 2022-05-15 08:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_vacancymodel_alter_servicesmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancymodel',
            name='body_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancymodel',
            name='body_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancymodel',
            name='body_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancymodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vacancymodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vacancymodel',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
