# Generated by Django 4.0.4 on 2022-05-19 04:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_projectformmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutinfomodel',
            options={'verbose_name': 'Biz haqimizda', 'verbose_name_plural': 'Biz haqimizda'},
        ),
        migrations.AlterModelOptions(
            name='certificatesmodel',
            options={'verbose_name': 'Sertifikatlar', 'verbose_name_plural': 'Sertifikatlar'},
        ),
        migrations.AlterModelOptions(
            name='partnercategorymodel',
            options={'verbose_name': 'Hamkorlar Kategoriyasi', 'verbose_name_plural': 'Hamkorlar Kategoriyasi'},
        ),
        migrations.AlterModelOptions(
            name='partnersmodel',
            options={'verbose_name': 'Hamkorlarimiz', 'verbose_name_plural': 'Hamkorlarimiz'},
        ),
        migrations.AlterModelOptions(
            name='portfoliomodel',
            options={'verbose_name': 'Bizning loyihalarimiz', 'verbose_name_plural': 'Bizning loyihalarimiz'},
        ),
        migrations.AlterModelOptions(
            name='projectformmodel',
            options={'verbose_name': 'Qoldirilgan arizalar', 'verbose_name_plural': 'Qoldirilgan arizalar'},
        ),
        migrations.AlterModelOptions(
            name='servicesmodel',
            options={'verbose_name': 'Bizning xizmatlar', 'verbose_name_plural': 'Bizning xizmatlar'},
        ),
        migrations.AlterModelOptions(
            name='vacancymodel',
            options={'verbose_name': 'Vakansiyalar', 'verbose_name_plural': 'Vakansiyalar'},
        ),
        migrations.AddField(
            model_name='aboutinfomodel',
            name='body_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutinfomodel',
            name='body_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutinfomodel',
            name='body_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
