# Generated by Django 4.0.4 on 2022-05-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_aboutinfomodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='body_uz',
            field=models.TextField(null=True),
        ),
    ]
