# Generated by Django 4.0.4 on 2022-05-31 06:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_portfoliomodel_body_en_portfoliomodel_body_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomodel',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='body_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='body_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='body_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
